#!/bin/bash

# Insert a shebang, delete the kickstart-specific portion,
# and make sure that the last command returns true.
sed -e '1i #!/bin/bash -x
/^#Begin Kickstart Script/,/^set -x/ d
/^%end/ c \
exit 0
' $1 > $2

sed -i -e 's/^\s*environment=ks/environment=sh/' $2

chmod +x $2
