#!/usr/bin/env ruby
# For use with OpenShift Enterprise 1.0 and 1.1
#
# This is an EXAMPLE script to show how you could monitor
# the capacity of a node using oo-stats and then alert
# a separate system to spin up new nodes as needed.
# It would need a lot of work to actually do that in any
# specific system.
#
# Installation: Place this script in the same directory
#   as the oo-stat script.
#
# Usage Example for new nodes at 50% capacity:
#   capacity-checker -t 50
#--
# Copyright 2013 Red Hat, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#++
load 'oo-stats'
require 'optparse'
require 'ostruct'

options = OpenStruct.new

opts = OptionParser.new do |opts|
  opts.banner = "Usage: capacity-checker [options]"

  opts.on("-v", "--verbose", "Run verbosely") do |v|
    options.verbose = v
  end

  opts.on("-t", "--threshold PERCENTAGE", Float,
          "Capacity threshold before adding nodes as a percentage (e.g. 50)") do |threshold|
    options.threshold = threshold
  end
end

opts.parse!

# Make sure a threshold was provided
unless options.threshold
  puts "ERROR:"
  puts " - Must supply a threshold value"
  puts ""
  puts opts.help
  exit 1
end

o = OOStats.new(:format => :yaml)
o.gather_statistics

# May want to consult the districts first to see if any need changes
o.results[:district_summaries].each do |district|
  # TODO
  # treat the NONE district specially, its capacity is always 0
  # For districts with effective available gears < available active gears,
  #   consider adding capacity if possible, or if up against the 6000 limit,
  #   consider compacting by removing a node.
  # For districts with very high active usage but plenty of capacity,
  #   consider adding a node to that district.
  #
end

# Calculate capacity by seeing if any of the profiles
# are over the specified capacity
o.results[:profile_summaries].each do |profile|
  usage_perct = profile[:gears_active_count].to_f / (profile[:available_active_gears] + profile[:gears_active_count]).to_f * 100
  puts "Current usage = #{usage_perct}%"
  if usage_perct >= options.threshold
    # TODO - create a new district in this profile
    # then create some nodes
    # then add them to the new district
    puts "OpenShift Hungry!! Need more nodes!!"
  end
end


