source 'https://rubygems.org'

# Gem dependencies live in oo-originator.gemspec
gemspec

gem 'bundler', '1.10.6'
gem 'highline', '1.6.19'
gem 'i18n', '0.6.5'
gem 'net-ssh', '2.7.0'
gem 'rake', '10.4.2'
gem 'rspec', '2.14.1'
gem 'rspec-core', '2.14.5'
gem 'rspec-expectations', '2.14.3'
gem 'rspec-mocks', '2.14.3'
gem 'terminal-table', '1.4.5'
gem 'thor', '0.19.1'
