require 'bundler/gem_tasks'
require 'installer/helpers'

include Installer::Helpers

task :package do
  @tmpdir = ENV['TMPDIR'] || '/tmp/'
  @package_dir = "#{gem_root_dir}/package"

  # Clear out the old package dir before making the new package
  if Dir.entries(gem_root_dir).include?('package')
    system 'rm', '-rf', @package_dir
  end

  # Set up a new package / archive name
  pkgname = "oo-install-#{Time.now.getutc.strftime('%Y%m%d-%H%M')}"

  # Copy the installer source to $TMPDIR
  system "cp -r #{gem_root_dir} #{@tmpdir}"
  system "mv #{@tmpdir}/oo-install #{@tmpdir}/#{pkgname}"

  # Recreate the package dir
  Dir.mkdir(@package_dir)

  # Zip up the source and copy it to the package dir
  system "cd #{@tmpdir}; zip -qq -r #{pkgname}.zip #{pkgname}"
  system 'mv', "#{@tmpdir}#{pkgname}.zip", @package_dir
  system 'rm', '-rf', "#{@tmpdir}oo-install*"

  # Copy the bootstrap file to the package dir
  system 'cp', 'oo-install-bootstrap.sh', "#{@package_dir}/index.html"
  system "sed -i .bak 's/INSTALLPKGNAME/#{pkgname}/g' #{@package_dir}/index.html"
  system 'rm', "#{@package_dir}/index.html.bak"
end
