#!/bin/bash

cp -f $1 $2

# set the default base url to our internal puddles
sed -i -e '
/repos_base_default=.*/ a\
repos_base_default=http://buildvm-devops.usersys.redhat.com/puddle/build/OpenShiftEnterprise/1.0.x/latest
s/^gpgcheck=0/gpgcheck=0\nsslverify=false/g' $2

# update the console msg with useful stuff
sed -i -e '
/^echo_installation_intentions$/ a\
configure_console_msg
' $2

# allow installation of carts to proceed as possible even if packaging is borked
sed -i -e 's/#\(carts.*--skip-broken\)/\1/' $2

# configure RHEL to use internal repo
ruby -p -i -e 'if $_ =~ /# configure RHEL subscription or repos here/; $_ = "  #" + $_[2..-1] + "  cat <<EOF > /etc/yum.repos.d/rhel.repo\n" + File.open("internal/rhel.repo").read + "\nEOF\n" end' $2

# configure RHEL to use internal repo for JBossEAP
ruby -p -i -e 'if $_ =~ /# configure JBossEAP subscription/; $_ = "  #" + $_[2..-1] + "  cat <<EOF > /etc/yum.repos.d/jbosseap.repo\n" + File.open("internal/jbosseap.repo").read + "\nEOF\n" end' $2

# configure RHEL to use internal repo for JBossEWS
ruby -p -i -e 'if $_ =~ /# configure JBossEWS subscription/; $_ = "  #" + $_[2..-1] + "  cat <<EOF > /etc/yum.repos.d/jbossews.repo\n" + File.open("internal/jbossews.repo").read + "\nEOF\n" end' $2

